services:
  docs:
    image: smart_physio_local_docs
    container_name: smart_physio_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./smart_physio:/app/smart_physio:z
    ports:
      - '9000:9000'
    command: /start-docs
