# Generated by Django 5.1.9 on 2025-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0002_patient_patientattachment_treatmentprogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='session_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('walk_in', 'Walk-in')], default='scheduled', max_length=20),
        ),
    ]
