# Generated by Django 5.1.9 on 2025-07-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0004_leadsource_patient_source_of_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='patient',
        ),
    ]
