# Generated by Django 5.1.9 on 2025-07-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0005_remove_treatmentsession_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='consultation_doctor',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='session_type',
        ),
    ]
