# Generated by Django 5.1.9 on 2025-07-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0007_patientconsultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='prescribed_medications',
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='treatment_plan',
        ),
    ]
