# Generated by Django 5.1.9 on 2025-07-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0008_remove_patientconsultation_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='kop.branch'),
            preserve_default=False,
        ),
    ]
