# Generated by Django 5.1.9 on 2025-07-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0009_patientconsultation_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='branch',
        ),
    ]
