# Generated by Django 5.1.9 on 2025-07-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0012_invoice_created_at_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patienttreatment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='patienttreatment',
            unique_together={('patient', 'is_active', 'treatment_program')},
        ),
    ]
