# Generated by Django 5.1.9 on 2025-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0014_branchadmin_delete_branchadminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name='BranchAdmin',
        ),
    ]
