# Generated by Django 5.1.9 on 2025-08-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kop', '0019_invoice_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='primary_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='secondary_diagnosis',
            field=models.TextField(blank=True),
        ),
    ]
